// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjonXbw1Pefy37LQ1m2TwNlTorIX9yrFI',
    appId: '1:675752247060:web:4c42fc3b0abdd7c5fc4c01',
    messagingSenderId: '675752247060',
    projectId: 'flutter-portfolio-e116e',
    authDomain: 'flutter-portfolio-e116e.firebaseapp.com',
    databaseURL: 'https://flutter-portfolio-e116e.firebaseio.com',
    storageBucket: 'flutter-portfolio-e116e.appspot.com',
    measurementId: 'G-WSQ43BSZFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_rIY0r0_SzELhhbLYe5BHHgJcMS0lZM',
    appId: '1:675752247060:android:4636b3367fcaaecefc4c01',
    messagingSenderId: '675752247060',
    projectId: 'flutter-portfolio-e116e',
    databaseURL: 'https://flutter-portfolio-e116e.firebaseio.com',
    storageBucket: 'flutter-portfolio-e116e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQrvkcQRUN3TZ30XNh2jI0kyPt3iYSKs',
    appId: '1:675752247060:ios:e5011f00015a7070fc4c01',
    messagingSenderId: '675752247060',
    projectId: 'flutter-portfolio-e116e',
    databaseURL: 'https://flutter-portfolio-e116e.firebaseio.com',
    storageBucket: 'flutter-portfolio-e116e.appspot.com',
    iosClientId: '675752247060-np70a3ru643hdb82ehs5b3577ls0squu.apps.googleusercontent.com',
    iosBundleId: 'com.hhoa.flutterAppWeb',
  );
}
